import { z } from "zod";

const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Date must be YYYY-MM-DD").optional();
const page = z.coerce.number().int().min(1).default(1);
const pageSize = z.coerce.number().int().min(1).max(10000).default(25);
const optionalNumber = z.preprocess((value) => value === "" || value === undefined ? undefined : value, z.coerce.number().nonnegative().optional());
export const meetingFeeListQuerySchema = z.object({ search: z.string().trim().max(120).optional(), status: z.enum(["PAID", "PENDING"]).optional(), source: z.enum(["ONLINE", "MANUAL"]).optional(), minAmount: optionalNumber, maxAmount: optionalNumber, paidFrom: date, paidTo: date, hub: z.string().uuid("Hub must be a valid id").optional(), month: z.string().regex(/^\d{4}-\d{2}$/, "Month must be YYYY-MM").optional(), sort: z.enum(["paidAt", "name", "amount"]).default("paidAt"), page, pageSize }).superRefine((value, ctx) => { if (value.minAmount != null && value.maxAmount != null && value.minAmount > value.maxAmount) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["minAmount"], message: "Minimum amount cannot exceed maximum amount" }); });
export const memberFeeHistoryQuerySchema = z.object({ page, pageSize });
export const attendanceListQuerySchema = z.object({ search: z.string().trim().max(120).optional(), status: z.union([z.enum(["CONFIRMED", "PENDING", "ABSENT"]), z.array(z.enum(["CONFIRMED", "PENDING", "ABSENT"]))]).optional(), feeStatus: z.enum(["PAID", "PENDING"]).optional(), responded: z.enum(["yes", "no"]).optional(), confirmedFromTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, "Time must be HH:mm").optional(), confirmedToTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, "Time must be HH:mm").optional(), hub: z.string().uuid("Hub must be a valid id").optional(), weekStart: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Week must be YYYY-MM-DD").optional(), perfectMonth: z.enum(["true", "false"]).optional().transform((value) => value === "true"), page, pageSize }).transform((value) => ({ ...value, statuses: value.status ? (Array.isArray(value.status) ? value.status : value.status.split(",")) : [] }));
