const currency = (amount) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(amount || 0));
const categoryLabel = (category) => category.replace("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

const MonthlySummary = ({ summary, loading = false }) => <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm sm:p-6">
  <div className="mb-5"><h2 className="font-bold text-gray-900">Monthly Summary</h2><p className="text-sm text-gray-500">Meeting fees collected and hub expenses.</p></div>
  {loading ? <p className="text-sm text-gray-500">Loading summary...</p> : <><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Metric label="Total Collected" value={currency(summary?.totalCollected)} tone="text-green-700 bg-green-50" /><Metric label="Total Spent" value={currency(summary?.totalSpent)} tone="text-red-600 bg-red-50" /><Metric label="Balance" value={currency(summary?.balance)} tone={summary?.balance < 0 ? "text-red-600 bg-red-50" : "text-green-700 bg-green-50"} /></div><div className="mt-5"><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-400">Category breakdown</h3>{Object.entries(summary?.categoryBreakdown || {}).length ? <div className="space-y-2">{Object.entries(summary.categoryBreakdown).map(([category, amount]) => <div key={category} className="flex items-center justify-between rounded-xl bg-gray-50 px-3 py-2 text-sm"><span className="text-gray-700">{categoryLabel(category)}</span><strong className="text-gray-900">{currency(amount)}</strong></div>)}</div> : <p className="text-sm text-gray-500">No expenses recorded for this month.</p>}</div></>}
</section>;
const Metric = ({ label, value, tone }) => <div className={`rounded-xl px-4 py-3 ${tone}`}><p className="text-xs font-semibold uppercase tracking-wide opacity-70">{label}</p><p className="mt-1 text-xl font-extrabold">{value}</p></div>;
export default MonthlySummary;
