import { useEffect, useState } from "react";
import { Save, X } from "lucide-react";
import { listAdminHubs, updateMember } from "../../services/adminService";
import BirthdayFields from "../ui/BirthdayFields";

const EditMemberModal = ({ member, onClose, onSuccess }) => {
  const [hubs, setHubs] = useState([]);
  const [form, setForm] = useState({ fullName: member.fullName || "", businessName: member.businessName || "", businessCategory: member.businessCategory || "", businessLocation: member.businessLocation || "", businessDescription: member.businessDescription || "", productsServices: member.productsServices || "", hubId: member.hubId || "", membershipType: member.membershipType || "", membershipStatus: member.membershipStatus || "ACTIVE", birthMonth: member.birthMonth || "", birthDay: member.birthDay || "" });
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { listAdminHubs().then(setHubs); }, []);
  const set = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await updateMember(member.userId, { ...form, hubId: form.hubId || null }); onSuccess(); } catch (err) { setError(err.response?.data?.message || "Could not update member."); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="flex max-h-[calc(100dvh-2rem)] w-full max-w-lg flex-col rounded-2xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-gray-100 px-6 py-4"><h2 className="text-lg font-bold text-gray-900">Edit Member</h2><button type="button" onClick={onClose} className="text-gray-400 hover:text-gray-700"><X className="h-5 w-5" /></button></div><div className="grid gap-4 overflow-y-auto p-6 sm:grid-cols-2"><Field label="Name" value={form.fullName} onChange={set("fullName")} /><Field label="Business Name" value={form.businessName} onChange={set("businessName")} /><Field label="Business Category" value={form.businessCategory} onChange={set("businessCategory")} /><Field label="Business Location" value={form.businessLocation} onChange={set("businessLocation")} /><label className="block text-sm font-semibold text-gray-800 sm:col-span-2">Business Description<textarea value={form.businessDescription} onChange={set("businessDescription")} rows={2} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-amber-400" /></label><label className="block text-sm font-semibold text-gray-800 sm:col-span-2">Products / Services<textarea value={form.productsServices} onChange={set("productsServices")} rows={2} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-amber-400" /></label><BirthdayFields month={form.birthMonth} day={form.birthDay} onChange={(key, value) => setForm((current) => ({ ...current, [key]: value }))} /><Select label="Hub" value={form.hubId} onChange={set("hubId")}><option value="">Not assigned</option>{hubs.map((hub) => <option key={hub.id} value={hub.id}>{hub.name}</option>)}</Select><Field label="Membership Type" value={form.membershipType} onChange={set("membershipType")} /><Select label="Status" value={form.membershipStatus} onChange={set("membershipStatus")}><option value="ACTIVE">Active</option><option value="PENDING_PAYMENT">Pending payment</option><option value="CANCELLED">Cancelled</option></Select></div>{error && <p className="px-6 text-sm text-red-600">{error}</p>}<div className="mt-2 flex justify-end gap-3 border-t border-gray-100 px-6 py-4"><button type="button" onClick={onClose} className="rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-semibold text-gray-600">Cancel</button><button disabled={saving} className="flex items-center gap-2 rounded-xl bg-amber-400 px-4 py-2.5 text-sm font-semibold text-gray-900 disabled:opacity-60"><Save className="h-4 w-4" />{saving ? "Saving..." : "Save changes"}</button></div></form></div>;
};
const Field = ({ label, ...props }) => <label className="block text-sm font-semibold text-gray-800">{label}<input required {...props} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm font-normal outline-none focus:border-amber-400" /></label>;
const Select = ({ label, children, ...props }) => <label className="block text-sm font-semibold text-gray-800">{label}<select {...props} className="mt-2 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm font-normal outline-none focus:border-amber-400">{children}</select></label>;
export default EditMemberModal;
