import { useEffect, useState } from "react";
import { Download, FileText, X } from "lucide-react";
import Sidebar from "../components/dashboard/Sidebar";
import DashboardHeader from "../components/dashboard/DashboardHeader";
import { getPosters } from "../services/posterService";
const fresh = (date) => date && Date.now() - new Date(date).getTime() < 14 * 86400000;
export default function Posters() {
  const [posters, setPosters] = useState([]), [selected, setSelected] = useState(null), [error, setError] = useState("");
  useEffect(() => { getPosters().then(setPosters).catch((e) => setError(e.message)); }, []);
  const pinned = posters.find((p) => p.isPinned), rest = posters.filter((p) => p.id !== pinned?.id);
  const card = (p, large = false) => <article key={p.id} className={`overflow-hidden rounded-2xl border bg-white shadow-sm ${large ? "md:grid md:grid-cols-2" : ""}`}><button className="block w-full bg-stone-100" onClick={() => p.fileType === "IMAGE" && setSelected(p)}>{p.fileType === "IMAGE" ? <img src={p.fileUrl} alt={p.title} className={`w-full object-contain ${large ? "max-h-[460px]" : "h-56"}`}/> : <div className="flex h-56 items-center justify-center gap-2 text-gray-500"><FileText /> PDF announcement</div>}</button><div className="p-5"><div className="flex gap-2 text-xs font-medium"><span className="text-green-700">{p.category.replaceAll("_", " ")}</span>{fresh(p.publishedAt) && <span className="rounded bg-amber-100 px-2 py-0.5 text-amber-800">New</span>}</div><h2 className="mt-2 text-lg font-bold text-gray-900">{p.title}</h2>{p.caption && <p className="mt-2 text-sm leading-6 text-gray-600">{p.caption}</p>}<div className="mt-4 flex gap-3 text-sm font-semibold text-green-700">{p.fileType === "PDF" && <a href={p.fileUrl} target="_blank" rel="noreferrer">View PDF</a>}<a href={p.fileUrl} download>Download <Download className="inline h-4"/></a></div></div></article>;
  return <div className="flex min-h-screen bg-stone-50"><Sidebar/><div className="min-w-0 flex-1"><DashboardHeader/><main className="px-4 py-6 sm:px-6 md:p-8"><h1 className="text-2xl font-bold">Guides &amp; Announcements</h1><p className="mt-1 text-gray-500">Helpful updates from your VedaConnect community.</p>{error ? <p className="mt-6 text-red-600">{error}</p> : !posters.length ? <p className="mt-6 rounded-xl border border-dashed bg-white p-6 text-gray-500">No guides or announcements have been published yet.</p> : <><div className="mt-6">{pinned && card(pinned, true)}</div><div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{rest.map((p) => card(p))}</div></>}{selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4"><button onClick={() => setSelected(null)} className="absolute right-4 top-4 text-white" aria-label="Close"><X/></button><div className="max-h-full max-w-full overflow-auto"><img src={selected.fileUrl} alt={selected.title} className="max-h-[85vh] max-w-full object-contain"/><a href={selected.fileUrl} download className="mt-3 inline-block rounded-xl bg-amber-400 px-4 py-2 font-semibold">Download</a></div></div>}</main></div></div>;
}
