import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Filter, Search, X } from "lucide-react";
import AdminSidebar from "../../components/admin/AdminSidebar";
import AdminHeader from "../../components/admin/AdminHeader";
import PeriodHubFilter from "../../components/admin/PeriodHubFilter";
import { usePeriodRange } from "../../hooks/usePeriodRange";
import { exportAdminMeetingList, getAdminAttendance, getAdminMeetingFees, getAdminMemberMeetingFees, listAdminHubs } from "../../services/adminService";

const defaults = { search: "", status: "", hub: "", responded: "", perfectMonth: "false", page: "1" };
const title = { fees: "Meeting Fee Status", attendance: "Attendance" };
const money = (amount) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(amount || 0));
const badge = (status) => status === "PAID" || status === "CONFIRMED" ? "bg-green-50 text-green-700" : status === "ABSENT" ? "bg-red-50 text-red-600" : "bg-amber-50 text-amber-700";
const inputDate = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

export default function AdminMeetingLists({ type }) {
  const [params, setParams] = useSearchParams(); const [data, setData] = useState(null); const [hubs, setHubs] = useState([]); const [open, setOpen] = useState(false); const [history, setHistory] = useState(null); const filtersRef = useRef(null); const periodState = usePeriodRange();
  const query = { ...defaults, ...Object.fromEntries(params.entries()) };
  const requestQuery = Object.fromEntries(Object.entries(query).filter(([, value]) => value !== "" && value !== "false"));
  if (type === "attendance") Object.assign(requestQuery, { period: periodState.period, rangeStart: inputDate(periodState.range.start), rangeEnd: inputDate(periodState.range.end) });
  else Object.assign(requestQuery, { month: inputDate(periodState.range.start).slice(0, 7) });
  const update = (next) => { const merged = { ...query, ...next, page: "1" }; Object.keys(merged).forEach((key) => !merged[key] || merged[key] === "false" ? delete merged[key] : null); setParams(merged); };
  useEffect(() => { listAdminHubs().then(setHubs); }, []);
  useEffect(() => { const timer = setTimeout(() => (type === "fees" ? getAdminMeetingFees(requestQuery) : getAdminAttendance(requestQuery)).then(setData).catch(() => setData({ rows: [], pagination: { total: 0 } })), 300); return () => clearTimeout(timer); }, [type, params, periodState.period, periodState.range.value]);
  useEffect(() => { if (!open) return undefined; const outside = (event) => { if (filtersRef.current && !filtersRef.current.contains(event.target)) setOpen(false); }; const escape = (event) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("mousedown", outside); document.addEventListener("keydown", escape); return () => { document.removeEventListener("mousedown", outside); document.removeEventListener("keydown", escape); }; }, [open]);
  const filters = Object.entries(requestQuery).filter(([key]) => !["search", "page", "month", "weekStart", "period", "rangeStart", "rangeEnd"].includes(key)); const rows = data?.rows || [];
  return <div className="flex min-h-screen bg-stone-50"><AdminSidebar /><div className="min-w-0 flex-1"><AdminHeader title={title[type]} /><main className="px-4 py-6 sm:px-6 md:p-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-gray-900">{title[type]}</h1>{type === "attendance" && <p className="mt-1 text-sm text-gray-500">Review attendance alongside the meeting fee for the selected period.</p>}</div><button type="button" onClick={() => exportAdminMeetingList(type, requestQuery)} className="rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-semibold">Export CSV</button></div><div className="mt-5"><PeriodHubFilter periodState={periodState} hub={query.hub || "all"} onHubChange={(value) => update({ hub: value === "all" ? "" : value })} hubs={hubs} /></div><div ref={filtersRef} className="relative mt-5 flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" /><input value={query.search} onChange={(event) => update({ search: event.target.value })} placeholder="Search member or business" className="w-full rounded-xl border border-gray-200 bg-white py-2.5 pl-10 pr-3" /></div><button type="button" onClick={() => setOpen((current) => !current)} aria-expanded={open} aria-controls="meeting-list-filters" className="rounded-xl border border-gray-200 bg-white px-4 text-sm font-semibold"><Filter className="mr-1 inline h-4 w-4" />Filters{filters.length ? ` (${filters.length})` : ""}</button>{open && <FilterPanel type={type} query={query} hubs={hubs} apply={(values) => { update(values); setOpen(false); }} reset={() => { setParams({}); setOpen(false); }} />}</div>{filters.length > 0 && <div className="mt-3 flex flex-wrap gap-2 text-xs">{filters.map(([key, value]) => <button type="button" key={key} onClick={() => update({ [key]: "" })} className="rounded-full bg-amber-100 px-3 py-1 text-amber-800">{key}: {value} <X className="inline h-3 w-3" /></button>)}</div>}<section className="mt-5 rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><div className="mb-3 text-sm text-gray-500">{type === "fees" ? `Filtered: ${money(data?.filteredTotals?.collected)} collected · ${money(data?.filteredTotals?.pendingAmount)} pending` : `${data?.filteredCount || 0} members match`}</div>{!data ? <p>Loading…</p> : !rows.length ? <div className="py-8 text-center text-gray-500">No members match your filters.</div> : type === "attendance" ? <AttendanceTable rows={rows} /> : <FeeTable rows={rows} onHistory={(userId) => getAdminMemberMeetingFees(userId, {}).then(setHistory)} />}</section>{history && <FeeHistory history={history} onClose={() => setHistory(null)} />}</main></div></div>;
}

const AttendanceTable = ({ rows }) => <div className="overflow-x-auto"><table className="min-w-[640px] w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="p-3">Member</th><th>Hub</th><th>Attendance</th><th>Responded</th></tr></thead><tbody>{rows.map((row) => <tr key={row.userId} className="border-b border-gray-50"><td className="p-3"><strong>{row.fullName}</strong><p className="text-xs text-gray-400">{row.businessName || "-"}</p></td><td>{row.hub}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${badge(row.status)}`}>{row.status}</span>{row.attendanceCount > 1 && <p className="mt-1 text-xs text-gray-400">{row.confirmedCount}/{row.attendanceCount} confirmed</p>}</td><td className="whitespace-nowrap">{row.respondedAt ? new Date(row.respondedAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }) : "-"}</td></tr>)}</tbody></table></div>;
const FeeTable = ({ rows, onHistory }) => <div className="overflow-x-auto"><table className="min-w-[680px] w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-400"><th className="p-3">Member</th><th>Business</th><th>Hub</th><th>Status</th><th>Amount</th><th>Paid at</th></tr></thead><tbody>{rows.map((row) => <tr key={row.userId} className="border-b border-gray-50"><td className="p-3 font-medium"><button type="button" className="text-green-700" onClick={() => onHistory(row.userId)}>{row.fullName}</button></td><td>{row.businessName || "-"}</td><td>{row.hub}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${badge(row.paymentStatus)}`}>{row.paymentStatus}</span></td><td>{money(row.amount)}</td><td>{row.paidAt ? new Date(row.paidAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }) : "-"}</td></tr>)}</tbody></table></div>;
const FeeHistory = ({ history, onClose }) => <div className="fixed inset-0 z-50 flex justify-end bg-black/30"><aside className="h-full w-full max-w-md bg-white p-6 shadow-xl"><button type="button" onClick={onClose} className="float-right"><X /></button><h2 className="font-bold">Member fee history</h2><div className="mt-4 space-y-2">{history.rows.map((row) => <p key={row.month} className="rounded-lg bg-gray-50 p-3">{row.month} · {row.paymentStatus} · {money(row.amount)}</p>)}</div></aside></div>;

function FilterPanel({ type, query, hubs, apply, reset }) { const [form, setForm] = useState(query); const change = (key) => (event) => setForm({ ...form, [key]: event.target.value }); return <div id="meeting-list-filters" className="absolute right-0 top-full z-20 mt-2 w-[min(34rem,calc(100vw-2rem))] rounded-2xl border border-amber-100 bg-white p-4 shadow-lg"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold text-gray-900">Filters</h2><button type="button" onClick={reset} className="text-sm font-medium text-gray-600 hover:text-gray-900">Reset</button></div><div className="grid gap-3 sm:grid-cols-2"><label>Attendance status<select value={form.status} onChange={change("status")} className="mt-1 w-full rounded-lg border p-2"><option value="">All</option>{["CONFIRMED", "PENDING", "ABSENT"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Hub<select value={form.hub} onChange={change("hub")} className="mt-1 w-full rounded-lg border p-2"><option value="">All hubs</option>{hubs.map((hub) => <option key={hub.id} value={hub.id}>{hub.name}</option>)}</select></label><label>Responded<select value={form.responded} onChange={change("responded")} className="mt-1 w-full rounded-lg border p-2"><option value="">Any</option><option value="yes">Yes</option><option value="no">No</option></select></label></div><div className="mt-4 flex justify-end"><button type="button" onClick={() => apply(form)} className="rounded-lg bg-amber-400 px-4 py-2 font-semibold">Apply</button></div></div>; }
