import { useEffect, useState } from "react";
import { Pencil, Plus, Receipt, Send, Trash2, X } from "lucide-react";
import AdminSidebar from "../../components/admin/AdminSidebar";
import AdminHeader from "../../components/admin/AdminHeader";
import MonthlySummary from "../../components/expenses/MonthlySummary";
import Dropdown from "../../components/ui/Dropdown";
import Pagination, { usePagination } from "../../components/ui/Pagination";
import Table, { Cell, HeaderCell } from "../../components/ui/Table";
import { listAdminHubs } from "../../services/adminService";
import { createExpense, deleteExpense, getExpenseNotificationLogs, getExpenses, getExpenseSummary, sendExpenseSummary, updateExpense } from "../../services/expenseService";

const categories = ["VENUE", "FOOD", "PRINTING", "DECORATION", "GUEST_SPEAKER", "MISCELLANEOUS", "OTHER"];
const label = (value) => value.replace("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const money = (amount) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(amount || 0));
const initialForm = (hubId = "") => ({ hubId, date: new Date().toISOString().slice(0, 10), category: "", amount: "", description: "", receiptUrl: "" });

const Expenses = () => {
  const [hubs, setHubs] = useState([]), [hubId, setHubId] = useState(""), [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [expenses, setExpenses] = useState([]), [logs, setLogs] = useState([]), [summary, setSummary] = useState(null), [form, setForm] = useState(initialForm()), [receipt, setReceipt] = useState(null), [editing, setEditing] = useState(null), [error, setError] = useState(""), [notice, setNotice] = useState(""), [saving, setSaving] = useState(false), [sending, setSending] = useState(false), [page, setPage] = useState(1), [logPage, setLogPage] = useState(1), [rows, setRows] = useState(10);
  const [year, monthNumber] = month.split("-").map(Number);
  const load = async () => { if (!hubId) return; const [items, totals, deliveryLogs] = await Promise.all([getExpenses({ hubId, month: monthNumber, year }), getExpenseSummary({ hubId, month: monthNumber, year }), getExpenseNotificationLogs({ hubId, month: monthNumber, year })]); setExpenses(items); setSummary(totals); setLogs(deliveryLogs); };
  useEffect(() => { listAdminHubs().then((data) => { setHubs(data); if (data[0]) { setHubId(data[0].id); setForm(initialForm(data[0].id)); } }); }, []);
  useEffect(() => { load().catch((err) => setError(err.message)); setPage(1); setLogPage(1); }, [hubId, month]);
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { if (editing) await updateExpense(editing.id, form, receipt); else await createExpense({ ...form, hubId }, receipt); setEditing(null); setForm(initialForm(hubId)); setReceipt(null); await load(); } catch (err) { setError(err.message || "Could not save expense."); } finally { setSaving(false); } };
  const edit = (expense) => { setEditing(expense); setReceipt(null); setForm({ hubId: expense.hubId, date: new Date(expense.date).toISOString().slice(0, 10), category: expense.category, amount: expense.amount, description: expense.description, receiptUrl: expense.receiptUrl || "" }); };
  const remove = async (id) => { if (!window.confirm("Delete this expense?")) return; try { await deleteExpense(id); await load(); } catch (err) { setError(err.message); } };
  const notify = async () => { setSending(true); setError(""); try { const result = await sendExpenseSummary({ hubId, month: monthNumber, year }); setNotice(`Summary sent: ${result.successCount} successful, ${result.failureCount} failed.`); await load(); } catch (err) { setError(err.message || "Could not send the summary."); } finally { setSending(false); } };
  const shownExpenses = usePagination(expenses, page, rows), shownLogs = usePagination(logs, logPage, rows);
  return <div className="flex min-h-screen bg-stone-50"><AdminSidebar /><div className="min-w-0 flex-1"><AdminHeader title="Expenses" /><main className="px-4 py-6 sm:px-6 md:p-8"><h1 className="text-2xl font-bold text-gray-900">Meeting Expenses</h1><p className="mb-6 text-gray-500">Track hub spending, balances, and month-end delivery status.</p><div className="mb-6 flex flex-col gap-3 sm:flex-row"><Dropdown value={hubId} onChange={(value) => { setHubId(value); setForm((state) => ({ ...state, hubId: value })); }} className="w-full sm:w-64" placeholder="Select hub" options={hubs.map((hub) => ({ value: hub.id, label: hub.name }))} /><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="vc-select min-h-11 rounded-xl px-4 py-2.5" /><button type="button" onClick={notify} disabled={!hubId || sending} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-green-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Send className="h-4 w-4" />{sending ? "Sending..." : "Send Month-End Summary Now"}</button></div>{notice && <p className="mb-4 rounded-xl border border-green-100 bg-green-50 px-4 py-3 text-sm text-green-700">{notice}</p>}{error && <p className="mb-4 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm text-red-600">{error}</p>}<MonthlySummary summary={summary} /><div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><ExpenseLog items={shownExpenses} onEdit={edit} onDelete={remove} /><ExpenseForm form={form} setForm={setForm} setReceipt={setReceipt} editing={editing} saving={saving} onCancel={() => { setEditing(null); setForm(initialForm(hubId)); }} onSubmit={save} /></div><Pagination page={page} onPageChange={setPage} rowsPerPage={rows} onRowsPerPageChange={(value) => { setRows(value); setPage(1); }} total={expenses.length} /><DeliveryLog items={shownLogs} /><Pagination page={logPage} onPageChange={setLogPage} rowsPerPage={rows} onRowsPerPageChange={(value) => { setRows(value); setLogPage(1); }} total={logs.length} /></main></div></div>;
};
const ExpenseLog = ({ items, onEdit, onDelete }) => <section className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm"><div className="px-4 py-4 sm:px-6"><h2 className="font-bold text-gray-900">Expense Log</h2><p className="text-sm text-gray-500">Admin-only records and receipts.</p></div><Table minWidth="min-w-[760px]"><thead><tr><HeaderCell align="center">Date</HeaderCell><HeaderCell>Category</HeaderCell><HeaderCell>Description</HeaderCell><HeaderCell align="right">Amount</HeaderCell><HeaderCell align="center">Receipt</HeaderCell><HeaderCell align="right">Actions</HeaderCell></tr></thead><tbody>{items.map((item) => <tr key={item.id}><Cell align="center">{new Date(item.date).toLocaleDateString("en-IN")}</Cell><Cell>{label(item.category)}</Cell><Cell title={item.description}>{item.description}</Cell><Cell align="right">{money(item.amount)}</Cell><Cell align="center">{item.receiptUrl ? <a href={item.receiptUrl} target="_blank" rel="noreferrer" className="text-green-700"><Receipt className="inline h-4 w-4" /></a> : "-"}</Cell><Cell align="right"><button type="button" onClick={() => onEdit(item)} className="mr-2 rounded-lg border border-gray-200 p-2"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => onDelete(item.id)} className="rounded-lg border border-red-200 p-2 text-red-600"><Trash2 className="h-4 w-4" /></button></Cell></tr>)}{!items.length && <tr><td colSpan={6} className="vc-cell text-center text-gray-500">No expenses recorded.</td></tr>}</tbody></Table></section>;
const ExpenseForm = ({ form, setForm, setReceipt, editing, saving, onCancel, onSubmit }) => <section className="h-fit rounded-2xl border border-gray-100 bg-white p-4 shadow-sm sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold text-gray-900">{editing ? "Edit Expense" : "Add Expense"}</h2>{editing && <button type="button" onClick={onCancel}><X className="h-5 w-5 text-gray-400" /></button>}</div><form onSubmit={onSubmit} className="space-y-4"><label className="block text-sm font-medium text-gray-700">Date<input required type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} className="vc-select mt-1.5 w-full rounded-xl px-3 py-2.5" /></label><label className="block text-sm font-medium text-gray-700">Category<Dropdown value={form.category} onChange={(value) => setForm({ ...form, category: value })} className="mt-1.5" placeholder="Select category" options={categories.map((category) => ({ value: category, label: label(category) }))} /></label><label className="block text-sm font-medium text-gray-700">Amount<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} className="vc-select mt-1.5 w-full rounded-xl px-3 py-2.5" /></label><label className="block text-sm font-medium text-gray-700">Description<textarea required rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="mt-1.5 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none" /></label><label className="block text-sm font-medium text-gray-700">Receipt (optional)<input type="file" accept="image/*,.pdf" onChange={(event) => setReceipt(event.target.files?.[0] || null)} className="mt-1.5 block w-full text-sm" /></label><button disabled={saving} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-amber-400 px-4 py-2.5 font-semibold text-gray-900 disabled:opacity-60"><Plus className="h-4 w-4" />{saving ? "Saving..." : editing ? "Save changes" : "Add Expense"}</button></form></section>;
const DeliveryLog = ({ items }) => <section className="mt-6 overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm"><div className="px-4 py-4 sm:px-6"><h2 className="font-bold text-gray-900">Month-End Delivery Status</h2><p className="text-sm text-gray-500">Every WhatsApp attempt is logged.</p></div><Table minWidth="min-w-[640px]"><thead><tr><HeaderCell>Member</HeaderCell><HeaderCell align="center">Status</HeaderCell><HeaderCell align="center">Sent At</HeaderCell><HeaderCell>Error</HeaderCell></tr></thead><tbody>{items.map((item) => <tr key={item.id}><Cell>{item.member?.memberProfile?.fullName || item.member?.email || "-"}</Cell><Cell align="center"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.status === "success" ? "bg-green-50 text-green-700" : "bg-red-50 text-red-600"}`}>{item.status}</span></Cell><Cell align="center">{new Date(item.sentAt).toLocaleString("en-IN")}</Cell><Cell title={item.errorMessage}>{item.errorMessage || "-"}</Cell></tr>)}{!items.length && <tr><td colSpan={4} className="vc-cell text-center text-gray-500">No delivery attempts for this month.</td></tr>}</tbody></Table></section>;
export default Expenses;
